---
title: "MTT#2 Cell Density"
author: "Andrés Gordo"
date: "2023-06-23"
output:
  pdf_document: 
    fig_caption: yes
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Tidying the data

First, I load the libraries needed and read the raw data from **Omega** in *.xlsx*. Then I create my **tidy data** selecting the proper values and assigning them to their corresponding **cell density**.

```{r,message=FALSE, warning=FALSE, echo=TRUE}
library(ggpubr)
library(readxl)
library(caret)
library(dplyr)
library(tidyr)
mtt_raw <- read_excel("C:\\Users\\andre\\OneDrive - unizar.es\\Laboratorio\\UCL ILDH 2023\\Results\\MTT\\MTT2_ANDRES_PDX_266.xlsx", col_names = FALSE)
mtt_tidy<-data.frame(absorbance=unlist(mtt_raw[4:9,3:10]), density=0)
mtt_tidy<-mtt_tidy[1:45,] #This assigns the absorbances to the cell density
mtt_tidy[1:12, 2]<- 2000
mtt_tidy[13:24, 2]<- 5000
mtt_tidy[25:36, 2]<- 8000
mtt_tidy[37:45, 2]<- 10000
```

## Plotting with ggplot

Violin plot with boxplot, adding a two sample *t test* for significance.

```{r, echo=TRUE}

density_comparisons<-list( c("2000", "5000"), 
                         c("5000", "8000"),c("8000", "10000"))
violin<- ggviolin(mtt_tidy,
          x          = "density", 
          y          = "absorbance", 
          title      = "MTT#1 Results & Analysis",
          xlab       = "Number of Cells seeded",
          ylab       = "Absorbance",
          fill       = "density",
          palette = c("#c994c7", "#df65b0", "#980043", "#67001f"),
          alpha      = 0.8,
          add        = "boxplot",
          add.params = list(fill = "white")) +
  stat_compare_means(comparisons = density_comparisons, 
                     label       = "p.signif", method="t.test")
 
  
violin
```
## Comparing MTT´s
```{r}
mtt_andres<-mtt_tidy %>%
  group_by(density)%>%
  summarise(mean_abs<-mean(absorbance))%>%
  rename("Andrés"="mean_abs <- mean(absorbance)")

mtt_maria<-read_excel("C:\\Users\\andre\\OneDrive - unizar.es\\Laboratorio\\UCL ILDH 2023\\Results\\MTT\\MTT1_ANDRES_PDX_236.xlsx", col_names = FALSE)
mtt_maria<-data.frame(absorbance=unlist(mtt_maria[4:9,3:10]), density=0)
mtt_maria<-mtt_maria[1:45,] #This assigns the absorbances to the cell density
mtt_maria[1:12, 2]<- 2000
mtt_maria[13:24, 2]<- 5000
mtt_maria[25:36, 2]<- 8000
mtt_maria[37:45, 2]<- 10000
mtt_maria<-mtt_maria %>%
  group_by(density)%>%
  summarise(mean_abs<-mean(absorbance))%>%
  rename("María"="mean_abs <- mean(absorbance)")

mtt1_2<-merge(mtt_andres,mtt_maria)
```
```{r}
mtt1_2 %>%gt() %>%
  tab_header(title="Absorbances table") %>%
  tab_style(
  style = list(cell_fill(color = "#b2f7ef"),
  cell_text(weight = "bold")),
  locations = cells_body(columns = Andrés))%>%
  tab_style(
  style = list(cell_fill(color = "#ffefb5"),
  cell_text(weight ="bold")), 
  locations = cells_body(columns = María))
```
```{r}
mtt12_tidy <- pivot_longer(mtt1_2, cols = c("Andrés", "María"), names_to = "person", values_to = "mean_absorbance")

custom_palette <- c("#b2f7ef", "#ffefb5")

# Create the plot
g <- ggplot(mtt12_tidy, aes(x = factor(density), y = mean_absorbance, fill = person)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = custom_palette) +
  theme_minimal() +  # Use a minimal theme for a professional look
  labs(x = "Density", y = "Mean Absorbance", fill = "Person") +  # Set axis and legend labels
  theme(
    plot.title = element_text(size = 16, face = "bold"),  # Customize the title
    axis.title = element_text(size = 12, face = "bold"),  # Customize the axis titles
    axis.text = element_text(size = 10),  # Adjust the axis text size
    legend.position = "right",  # Move the legend to the right
    legend.title = element_text(size = 10),  # Customize the legend title size
    legend.text = element_text(size = 8),  # Adjust the legend text size
    panel.grid.major.y = element_blank()  # Remove horizontal gridlines
  )
```





