---
title: "2º MTT BPD Dark vs Light"
author: "Andrés Gordo"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE, warning=FALSE, echo=FALSE}
library(ggpubr)
library(readxl)
library(caret)
library(dplyr)
library(tidyr)
library(plotly)
library(gt)
library(dr4pl)
mtt_raw <- read_excel("C:\\Users\\andre\\OneDrive - unizar.es\\Laboratorio\\UCL ILDH 2023\\Results\\MTT\\MTT10_ANDRES_PDX_217.xlsx", col_names = FALSE)
mtt_tidy<-data.frame(absorbance=unlist(mtt_raw[4:9,3:11]), density=0)
mtt_tidy<-mtt_tidy[1:53,] #This assigns the absorbances to the cell density
mtt_tidy[1:6, 2]<- "Control_1"
mtt_tidy[7:12, 2]<- 0.01
mtt_tidy[13:18, 2]<- 0.05
mtt_tidy[19:24, 2]<- 0.075
mtt_tidy[25:30, 2]<- 0.1
mtt_tidy[31:36, 2]<- 0.15
mtt_tidy[37:42, 2]<- 0.2
mtt_tidy[43:48, 2]<- 0.3
mtt_tidy[49:53, 2]<- "Control_2"
mtt_tidy<-mtt_tidy[-c(4:5),]
```

## BPD Dark
```{r,message=FALSE, warning=FALSE, echo=FALSE}
custom_colors <- rep("purple", 9)
mtt_tidy_2<-mtt_tidy%>%
  group_by(density)%>%
  mutate("mean_abs"=mean(absorbance), "sd_absorbance"=sd(absorbance))
names(mtt_tidy_2)<-c("absorbance", "concentration_bpd", "mean","sd")
custom_order <- c("Control_1", "0.01", "0.05", "0.075", "0.1", "0.15", "0.2", "0.3", "Control_2")

# Reorder the "concentration_bpd" factor based on the custom order
mtt_tidy_2$concentration_bpd <- factor(mtt_tidy_2$concentration_bpd, levels = custom_order)

# Create the plot
g <- ggplot(mtt_tidy_2, aes(x = concentration_bpd, y = absorbance, fill = concentration_bpd)) +
  geom_bar(stat = "summary", position = "dodge") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), position = position_dodge(width = 0.9), width = 0.25) +
  labs(x = "BPD Concentration (µMolar)", y = "Absorbance", title="BPD Dark MTT 10k cells/well") +
  theme_minimal()+scale_fill_manual(values = custom_colors)+guides(fill = FALSE)

g
```
***The absorbance peak in both 0.15 and 0.2 uM BPD is most likely due to wrongly adding 110 uL to those wells, instead of 100 uL like the rest.***

## BPD Light
At **2.5 J/cm<sup>2</sup>**, during **5 minutes and 52 seconds**.
The Inhibitory Concentration 50 -*IC50*-, calculated with dr4pl is also shown
```{r,message=FALSE, warning=FALSE, echo=FALSE}
mtt_raw <- read_excel("C:\\Users\\andre\\OneDrive - unizar.es\\Laboratorio\\UCL ILDH 2023\\Results\\MTT\\MTT11_ANDRES_PDX_217.xlsx", col_names = FALSE)
mtt_tidy<-data.frame(absorbance=unlist(mtt_raw[4:9,3:11]), density=0)
mtt_tidy<-mtt_tidy[1:54,] #This assigns the absorbances to the cell density
mtt_tidy[1:6, 2]<- "Control_1"
mtt_tidy[7:12, 2]<- 0.01
mtt_tidy[13:18, 2]<- 0.05
mtt_tidy[19:24, 2]<- 0.075
mtt_tidy[25:30, 2]<- 0.1
mtt_tidy[31:36, 2]<- 0.15
mtt_tidy[37:42, 2]<- 0.2
mtt_tidy[43:48, 2]<- 0.3
mtt_tidy[49:54, 2]<- "Control_2"
```


```{r,message=FALSE, warning=FALSE, echo=FALSE}
custom_colors <- c("#320E83", rev(c("#D8BFD8", "#C8A2C8", "#DA70D6","#8A58FF", "#A020F0", "#8A2BE2", "#4B0082")), "#320E83")
mtt_tidy_2<-mtt_tidy%>%
  group_by(density)%>%
  mutate("mean_abs"=mean(absorbance), "sd_absorbance"=sd(absorbance))
names(mtt_tidy_2)<-c("absorbance", "concentration_bpd", "mean","sd")
custom_order <- c("Control_1", "0.01", "0.05", "0.075", "0.1", "0.15", "0.2", "0.3", "Control_2")

# Reorder the "concentration_bpd" factor based on the custom order
mtt_tidy_2$concentration_bpd <- factor(mtt_tidy_2$concentration_bpd, levels = custom_order)

# Calculates IC50
IC_data<-filter(mtt_tidy,density!="Control_1" & density!="Control_2")
IC_data<-dr4pl(absorbance~as.numeric(density), data=IC_data)
IC50<-IC(IC_data, inhib.percent = 50)

# Create the plot
g <- ggplot(mtt_tidy_2, aes(x = concentration_bpd, y = absorbance, fill = concentration_bpd)) +
  geom_bar(stat = "summary", position = "dodge") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), position = position_dodge(width = 0.9), width = 0.25) +
  labs(x = "BPD Concentration (µMolar)", y = "Absorbance", title="BPD Light MTT 10k cells/well") +
  theme_minimal()+scale_fill_manual(values = custom_colors)+guides(fill = FALSE) + annotate("text", x = Inf, y = Inf, hjust = 1.4, vjust = 1, label = paste("IC50 for BPD Light  is", round(IC50,digits = 4), sep=" "),fontface = 'italic')

g

```